Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2022-03, with the labels that each got.

#183 Fix duplicate results in callback
  qiskit_ibm_runtime/runtime_job.py
  test/integration/test_results.py
Labels: backport potential

#196 Update wait for final state (#194)
  qiskit_ibm_runtime/runtime_job.py
  releasenotes/notes/wait-for-final-state-bug-02ebbe8df7a252d0.yaml
  test/integration/test_job.py
Labels: Changelog: Bugfix

#220 Fix error when just one QuantumCircuit is passed to primitives
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
  releasenotes/notes/fix-error-single-circuit-89a0e7b64deedbaa.yaml
  test/integration/test_ibm_sampler.py
Labels: Changelog: Bugfix, backport potential

#215 Bump version post release to 0.3.0
  docs/conf.py
  qiskit_ibm_runtime/VERSION.txt
Labels: on hold

#226 Deprecate auth parameter and add new channel parameter
  .github/workflows/ci.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/integration-tests.yml
  CONTRIBUTING.md
  README.md
  constraints.txt
  docs/max_time.rst
  docs/release_notes.rst
  docs/tutorials/01_introduction_ibm_cloud_runtime.ipynb
  docs/tutorials/02_introduction_ibm_quantum_runtime.ipynb
  docs/tutorials/03_backends.ipynb
  docs/tutorials/04_account_management.ipynb
  docs/tutorials/qka.ipynb
  docs/tutorials/sample_expval_program/qiskit_runtime_expval_program.ipynb
  docs/tutorials/vqe.ipynb
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/accounts/__init__.py
  qiskit_ibm_runtime/accounts/account.py
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/accounts/storage.py
  qiskit_ibm_runtime/api/auth.py
  qiskit_ibm_runtime/api/client_parameters.py
  qiskit_ibm_runtime/api/clients/auth.py
  qiskit_ibm_runtime/constants.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/ibm_estimator.py
  qiskit_ibm_runtime/ibm_runtime_service.py
  qiskit_ibm_runtime/ibm_sampler.py
  qiskit_ibm_runtime/runtime_options.py
  qiskit_ibm_runtime/utils/utils.py
  releasenotes/notes/add-channel-deprecate-auth-4e021efeb527818c.yaml
  test/account.py
  test/decorators.py
  test/e2e/test_tutorials.py
  test/ibm_test_case.py
  test/integration/test_account.py
  test/integration/test_auth_client.py
  test/integration/test_backend.py
  test/integration/test_backend_serialization.py
  test/integration/test_basic_server_paths.py
  test/integration/test_job.py
  test/integration/test_proxies.py
  test/integration/test_retrieve_job.py
  test/unit/mock/fake_quantum_auth_client.py
  test/unit/mock/fake_runtime_client.py
  test/unit/mock/fake_runtime_service.py
  test/unit/test_account.py
  test/unit/test_account_client.py
  test/unit/test_backend_retrieval.py
  test/unit/test_client_parameters.py
  test/unit/test_data_serialization.py
  test/unit/test_job_retrieval.py
  test/unit/test_jobs.py
  test/unit/test_programs.py
  test/unit/test_runtime_ws.py
  test/utils.py
Labels: Changelog: API Change
