Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2022-07, with the labels that each got.

#429 Bump min terra version to 0.21.0
  releasenotes/notes/fix-terra-min-version-613f427851adfab0.yaml
  requirements.txt
  setup.py
Labels: Changelog: Bugfix, backport potential

#430 Set optimization level default to 1 for alpha release
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
Labels: backport potential

#386 Update docs for run_options
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
Labels: documentation
