Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2022-06, with the labels that each got.

#379 Raise IBMNotAuthorizedError if token is incorrect
  qiskit_ibm_runtime/api/session.py
  releasenotes/notes/not-authorized-error-31241cd68d8a26d7.yaml
  test/integration/test_auth_client.py
Labels: Changelog: API Change

#310 Refactor to set qubit properties when constructing target
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/ibm_qubit_properties.py
  qiskit_ibm_runtime/utils/backend_converter.py
  releasenotes/notes/upgrade-qubit-properties-b5ff4a168ed0cc07.yaml
  test/integration/test_backend.py
Labels: Changelog: API Change

#385 Revert "Revert "(fix): deprecate class qiskit_ibm_runtime.IBMSampler for the next release""
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/ibm_sampler.py
  releasenotes/notes/0.4/deprecate-classes-ef077e50db9718bc.yaml
  releasenotes/notes/remove-ibm-sampler-7779165095fd2a5f.yaml
  test/integration/test_ibm_sampler.py
Labels: Changelog: Removal

#363 Removed deprecated qiskit_ibm_runtime.IBMEstimator class
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/ibm_estimator.py
  releasenotes/notes/remove-ibm-estimator-7f0b4da07c23e859.yaml
  test/integration/test_ibm_estimator.py
Labels: Changelog: Removal, on hold

#370 Use qiskitrc credentials if default config doesn't exist
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/accounts/storage.py
  releasenotes/notes/load-qiskitrc-creds-4aac54737333e248.yaml
  test/account.py
  test/unit/test_account.py
Labels: Changelog: New Feature
