Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-03, with the labels that each got.

#736 Use `ContextVar` for global variables to ensure thread safety
  qiskit_ibm_runtime/session.py
  test/unit/test_ibm_primitives.py
  test/unit/test_session.py
Labels: Changelog: New Feature

#743 Enable retrieval of historical data for 'target'
  qiskit_ibm_runtime/ibm_backend.py
  releasenotes/notes/target-history-93e8eca3abf49230.yaml
Labels: Changelog: New Feature

#692 add session_time param
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_options.py
  qiskit_ibm_runtime/runtime_session.py
  qiskit_ibm_runtime/session.py
  releasenotes/notes/0.9/session-time-param-b02d1513d9754b52.yaml
  test/program.py
  test/unit/mock/fake_runtime_client.py
  test/unit/test_session.py
Labels: Changelog: New Feature

#623 Set backend to none if not returned in job response
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/runtime_session.py
  releasenotes/notes/refresh-job-backend-1c4f9cbfa30edad4.yaml
  test/unit/test_jobs.py
  test/unit/test_runtime_ws.py
Labels: Changelog: Bugfix

#661 Honor the instance chosen when selecting a backend
  qiskit_ibm_runtime/hub_group_project.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/session.py
  releasenotes/notes/honor-instance-param-37b14111489364b0.yaml
  test/integration/test_session.py
  test/unit/test_ibm_primitives.py
  test/unit/test_session.py
Labels: Changelog: Bugfix

#772 Set error levels to default when no backend is selected
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
  releasenotes/notes/error-lvl-defaults-no-backend-95fba0e99884314a.yaml
Labels: Changelog: Bugfix

#774 Retrieve backends with runtime api
  qiskit_ibm_runtime/api/clients/__init__.py
  qiskit_ibm_runtime/api/clients/account.py
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/__init__.py
  qiskit_ibm_runtime/api/rest/account.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/hub_group_project.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  test/unit/mock/fake_account_client.py
  test/unit/mock/fake_runtime_client.py
  test/unit/mock/fake_runtime_service.py
  test/unit/test_account_client.py
Labels: Changelog: API Change
