Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-05, with the labels that each got.

#797 remove code deprecated after 0.7 release
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_options.py
  qiskit_ibm_runtime/sampler.py
  releasenotes/notes/remove-depreacted-f9abe2c7a47c3062.yaml
  test/integration/test_estimator.py
  test/integration/test_sampler.py
  test/unit/test_ibm_primitives.py
Labels: Changelog: Removal

#821 Update QPY to match Terra 0.24
  qiskit_ibm_runtime/qpy/binary_io/circuits.py
  qiskit_ibm_runtime/qpy/binary_io/schedules.py
  qiskit_ibm_runtime/qpy/binary_io/value.py
  qiskit_ibm_runtime/qpy/common.py
  qiskit_ibm_runtime/qpy/interface.py
  qiskit_ibm_runtime/qpy/type_keys.py
  requirements.txt
  setup.py
Labels: Changelog: New Feature

#858 Allow retrieval of backends even if a configuration is missing
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/retrieve-backends-no-config-5d51fdf5fe9af648.yaml
  test/integration/test_backend.py
Labels: Changelog: Bugfix

#859 Use qiskit-ibm-provider
  qiskit_ibm_runtime/accounts/account.py
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/api/client_parameters.py
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/backendreservation.py
  qiskit_ibm_runtime/hub_group_project.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/ibm_qubit_properties.py
  qiskit_ibm_runtime/proxies/__init__.py
  qiskit_ibm_runtime/proxies/configuration.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/qpy/__init__.py
  qiskit_ibm_runtime/qpy/binary_io/__init__.py
  qiskit_ibm_runtime/qpy/binary_io/circuits.py
  qiskit_ibm_runtime/qpy/binary_io/schedules.py
  qiskit_ibm_runtime/qpy/binary_io/value.py
  qiskit_ibm_runtime/qpy/common.py
  qiskit_ibm_runtime/qpy/exceptions.py
  qiskit_ibm_runtime/qpy/formats.py
  qiskit_ibm_runtime/qpy/interface.py
  qiskit_ibm_runtime/qpy/type_keys.py
  qiskit_ibm_runtime/utils/backend_converter.py
  qiskit_ibm_runtime/utils/backend_decoder.py
  qiskit_ibm_runtime/utils/hgp.py
  qiskit_ibm_runtime/utils/json.py
  requirements.txt
  setup.py
  test/integration/test_proxies.py
  test/unit/mock/fake_runtime_client.py
  test/unit/mock/proxy_server.py
  test/unit/test_account.py
  test/unit/test_client_parameters.py
  test/unit/test_job_retrieval.py
  test/unit/test_jobs.py
Labels: Changelog: Removal

#877 Support CouplingMap in options
  qiskit_ibm_runtime/options/options.py
  qiskit_ibm_runtime/options/simulator_options.py
  releasenotes/notes/support_coupling_map-3695cd8c7e5ad848.yaml
  test/unit/test_options.py
Labels: Changelog: New Feature
