Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-12, with the labels that each got.

#1249 Raise error if backend retrieved not in current instance
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/backend-instance-filter-20d69b3951437f19.yaml
  test/integration/test_backend.py
Labels: Changelog: New Feature

#1257 Fix backend_converter `faulty_qubit` name error
  qiskit_ibm_runtime/utils/backend_converter.py
  releasenotes/notes/faulity-qubits-name-error-f03b90f21cd2d9bf.yaml
Labels: Changelog: Bugfix

#1170 Don't block for the first job in a session
  qiskit_ibm_runtime/session.py
  releasenotes/notes/backend-blocking-job-70ebcf44855cbdfd.yaml
  test/integration/test_session.py
Labels: Changelog: Bugfix

#1278 Deprecate service.runtime
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/deprecate-service-runtime-1138cb5ec43fc4ff.yaml
Labels: Changelog: Deprecation

#1121 Removed support for qiskitrc file
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/accounts/storage.py
  test/account.py
  test/unit/test_account.py
Labels: Changelog: Removal
