Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-06, with the labels that each got.

#890 Give warning when backend is not active
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/non_active_backend-2fcdbbc3d902f2a3.yaml
Labels: Changelog: New Feature

#868 Use new `exclude_params` query when retrieving jobs
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/program_job.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/exclude-job-params-397b0b918aa4f6f9.yaml
  test/integration/test_retrieve_job.py
  test/unit/mock/fake_runtime_client.py
Labels: Changelog: API Change

#893 Disable default session
  docs/migrate/migrate-estimator.rst
  docs/migrate/migrate-sampler.rst
  docs/tutorials/how-to-getting-started-with-estimator.ipynb
  docs/tutorials/how-to-getting-started-with-sampler.ipynb
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  releasenotes/notes/remove-default-session-ba05e48362567d5b.yaml
  test/integration/test_estimator.py
  test/integration/test_sampler.py
  test/unit/test_estimator.py
  test/unit/test_ibm_primitives.py
  test/unit/test_session.py
Labels: Changelog: Deprecation, Changelog: New Feature

#913 "bss.seconds" deprecation in job.metrics()
  docs/cloud/plans.rst
  qiskit_ibm_runtime/options/utils.py
  qiskit_ibm_runtime/runtime_job.py
  test/unit/test_account.py
Labels: Changelog: Deprecation
