Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-08, with the labels that each got.

#979 Filter backends by instance when given in QiskitRuntimeService constructor
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/filter_instance-a7203041b5ab85d9.yaml
  test/decorators.py
  test/unit/test_backend_retrieval.py
Labels: Changelog: Bugfix

#976 Expose job cost estimation values
  qiskit_ibm_runtime/runtime_job.py
  releasenotes/notes/job-cost-estimation-d0ba83dbc95c3f67.yaml
  test/integration/test_job.py
Labels: Changelog: New Feature

#1000 Fix bug with custom header in request
  qiskit_ibm_runtime/api/session.py
Labels: Changelog: Bugfix

#866 Remove deprecation warning for unsupported parameters of transpilation settings
  qiskit_ibm_runtime/options/execution_options.py
  qiskit_ibm_runtime/options/options.py
  qiskit_ibm_runtime/options/resilience_options.py
  qiskit_ibm_runtime/options/simulator_options.py
  qiskit_ibm_runtime/options/transpilation_options.py
  releasenotes/notes/option_validation-79d26018ab770519.yaml
  test/unit/test_options.py
Labels: Changelog: New Feature

#1010 Don't store circuit params automatically
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/dont-store-circuit-params-9d87ffefc2a7d257.yaml
  test/integration/test_job.py
  test/serialization.py
  test/unit/mock/fake_runtime_client.py
Labels: Changelog: New Feature

#1031 Remove max circuits validation
  qiskit_ibm_runtime/base_primitive.py
  releasenotes/notes/remove-backend-circuits-limit-b804b58dc97ed276.yaml
  test/unit/test_ibm_primitives.py
Labels: Changelog: Removal

#1035 Deprecate noise amplification option
  qiskit_ibm_runtime/options/resilience_options.py
  qiskit_ibm_runtime/utils/deprecation.py
  releasenotes/notes/deprecate_noise_amplifier-e656cc98a962a81b.yaml
  test/unit/test_estimator.py
  test/unit/test_ibm_primitives.py
  test/unit/test_options.py
  test/utils.py
Labels: Changelog: Deprecation

#1032 Remove `migrate-qiskit-alg` tutorial
  docs/index.rst
  docs/migrate/migrate-guide.rst
  docs/migrate/migrate-qiskit-alg.rst
Labels: Changelog: Removal

#974 Data tracking improvements
  qiskit_ibm_runtime/api/session.py
  releasenotes/notes/data-tracking-updates-97327c62c51b5891.yaml
Labels: Changelog: New Feature
