Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-02, with the labels that each got.

#717 Fix "Rumtime" typo in Estimator tutorial
  docs/tutorials/how-to-getting-started-with-estimator.ipynb
  docs/tutorials/how-to-getting-started-with-sampler.ipynb
Labels: documentation

#719 Add backend filter to jobs()
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/jobs-backend-filter-05c55c56a7ebaa05.yaml
  test/integration/test_retrieve_job.py
  test/unit/mock/fake_runtime_client.py
Labels: Changelog: New Feature

#707 Added support for storing the account in a specified file-name
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/user-defined-filename-for-account-710cb32e812b3bd8.yaml
  test/unit/test_account.py
Labels: Changelog: New Feature

#663 Increased websocket connection retries to 8
  qiskit_ibm_runtime/api/clients/base.py
  qiskit_ibm_runtime/api/clients/runtime_ws.py
Labels: Changelog: Bugfix

#706 Fix bug with initializing service with channel parameter
  qiskit_ibm_runtime/accounts/management.py
Labels: Changelog: Bugfix

#628 Choose correct backend within a session
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  releasenotes/notes/session-backend-option-26ad05fcb7c96dc6.yaml
Labels: Changelog: Bugfix

#709 Support downloading result from external url
  qiskit_ibm_runtime/runtime_job.py
  test/unit/test_jobs.py
Labels: Changelog: New Feature

#729 Add ECR and CZ gate mapping
  qiskit_ibm_runtime/utils/backend_converter.py
  releasenotes/notes/custom-gate-transpile-bug-61b64e4937269f28.yaml
Labels: Changelog: Bugfix
