Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-10, with the labels that each got.

#1137 Update docstring & remove max_time in `from_id()`
  qiskit_ibm_runtime/session.py
Labels: Changelog: New Feature

#1119 Expose new session details
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/base.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/api/rest/runtime_session.py
  qiskit_ibm_runtime/session.py
  releasenotes/notes/expose-session-details-c4a44316d30dad33.yaml
Labels: Changelog: New Feature

#1093 Support only LocalFoldingAmplifier as noise_amplifier option
  docs/how_to/error-mitigation.rst
  qiskit_ibm_runtime/options/resilience_options.py
  test/unit/test_estimator.py
Labels: documentation

#1143 Fix target_history date bug
  qiskit_ibm_runtime/ibm_backend.py
  releasenotes/notes/target-history-date-bug-7d6dad84fc5b3d2e.yaml
  test/integration/test_backend.py
Labels: Changelog: Bugfix

#1150 Log instance on initialization and when running a job
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/log-instance-selected-a18c4791418b5e0d.yaml
  test/integration/test_account.py
Labels: Changelog: New Feature

#1152 Fix link to `Close a session`
  docs/sessions.rst
Labels: documentation

#1139 Allow users to indicate they are done submitting jobs to a session
  docs/how_to/backends.rst
  docs/how_to/error-mitigation.rst
  docs/how_to/error-suppression.rst
  docs/how_to/run_session.rst
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/api/rest/runtime_session.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_session.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  releasenotes/notes/session-accepting-jobs-d7ef6b60c0f5527b.yaml
  test/integration/test_estimator.py
  test/integration/test_options.py
  test/integration/test_sampler.py
  test/integration/test_session.py
  test/unit/test_estimator.py
  test/unit/test_sampler.py
  test/unit/test_session.py
Labels: Changelog: New Feature, on hold
