Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-11, with the labels that each got.

#1153 Add deprecation warnings for everything related to custom programs
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/deprecate-custom-programs-274e6ea20d1027a1.yaml
  test/unit/test_programs.py
Labels: Changelog: Deprecation

#1183 Create batch class
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/batch.py
  releasenotes/notes/batch-class-b7a3befcfce8860e.yaml
  test/unit/test_batch.py
Labels: Changelog: New Feature

#1205 Remove caching of results in RuntimeJob
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/utils/utils.py
  releasenotes/notes/no_cached_results-54d063390b9b0ae6.yaml
  test/integration/test_ibm_job.py
  test/integration/test_ibm_job_attributes.py
Labels: Changelog: API Change

#1193 Add channel strategy instance validation
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/channel-strategy-instance-validate-639b18b8c5d44678.yaml
Labels: Changelog: New Feature

#1220 Fix BYOB job results bytes typing issue
  qiskit_ibm_runtime/runtime_job.py
  releasenotes/notes/byte-result-bug-7afb5abe813f5b1b.yaml
  test/unit/test_jobs.py
Labels: Changelog: Bugfix

#1219 Added deprecation warning when using qiskitrc file
  qiskit_ibm_runtime/accounts/management.py
  releasenotes/notes/deprecate_qiskitrc-1fd8afc6d599fc0e.yaml
  test/ibm_test_case.py
  test/unit/test_account.py
Labels: Changelog: Deprecation

#1163 Update session.from_id()
  qiskit_ibm_runtime/session.py
  releasenotes/notes/from-id-params-659a2adb727b9d18.yaml
  test/integration/test_session.py
Labels: Changelog: Bugfix, Changelog: Deprecation

#1192 Remove all code related to custom programs
  Makefile
  docs/migrate/migrate-setup.rst
  program_source/__init__.py
  program_source/circuit_runner/__init__.py
  program_source/circuit_runner/circuit_runner.json
  program_source/circuit_runner/circuit_runner.py
  program_source/version.py
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/program.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/constants.py
  qiskit_ibm_runtime/program/__init__.py
  qiskit_ibm_runtime/program/program_backend.py
  qiskit_ibm_runtime/program/program_metadata_sample.json
  qiskit_ibm_runtime/program/program_template.py
  qiskit_ibm_runtime/program/user_messenger.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/runtime_program.py
  qiskit_ibm_runtime/session.py
  qiskit_ibm_runtime/utils/estimator_result_decoder.py
  qiskit_ibm_runtime/utils/result_decoder.py
  qiskit_ibm_runtime/utils/runner_result.py
  qiskit_ibm_runtime/utils/sampler_result_decoder.py
  releasenotes/notes/remove-custom-programs-aea76f4dd19cd481.yaml
  test/ibm_test_case.py
  test/integration/test_job.py
  test/integration/test_program.py
  test/integration/test_proxies.py
  test/program.py
  test/serialization.py
  test/templates.py
  test/unit/mock/fake_runtime_client.py
  test/unit/test_job_retrieval.py
  test/unit/test_jobs.py
Labels: Changelog: Removal

#1233 Instance & channel_strategy validation
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/q-ctrl-instance-check-46181d51f16d18bc.yaml
  test/unit/mock/fake_runtime_client.py
Labels: Changelog: Bugfix
