Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2023-07, with the labels that each got.

#871 Use qiskit-ibm-provider api code
  qiskit_ibm_runtime/api/clients/__init__.py
  qiskit_ibm_runtime/api/clients/auth.py
  qiskit_ibm_runtime/api/clients/backend.py
  qiskit_ibm_runtime/api/clients/base.py
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/clients/runtime_ws.py
  qiskit_ibm_runtime/api/clients/version.py
  qiskit_ibm_runtime/api/rest/__init__.py
  qiskit_ibm_runtime/api/rest/backend.py
  qiskit_ibm_runtime/api/rest/base.py
  qiskit_ibm_runtime/api/rest/cloud_backend.py
  qiskit_ibm_runtime/api/rest/program.py
  qiskit_ibm_runtime/api/rest/program_job.py
  qiskit_ibm_runtime/api/rest/root.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/api/rest/runtime_session.py
  qiskit_ibm_runtime/runtime_job.py
  requirements.txt
  setup.py
  test/integration/test_auth_client.py
  test/integration/test_proxies.py
Labels: Changelog: API Change, Changelog: Removal

#876 Add SimulatorOptions.set_backend method
  docs/how_to/noisy_simulators.rst
  qiskit_ibm_runtime/options/simulator_options.py
  releasenotes/notes/simulator-options-set-backend-796e2ae4517be689.yaml
  requirements-dev.txt
  test/unit/test_options.py
Labels: Changelog: New Feature

#950 Support updating job tags
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/runtime_job.py
  releasenotes/notes/support-update-tags-43eb9478a315c2b3.yaml
  test/integration/test_job.py
Labels: Changelog: New Feature

#939 Raise exception when number of circuits exceeds maximum circuits allowed on backendkend max_circuits
  qiskit_ibm_runtime/base_primitive.py
  releasenotes/notes/max_circuits-b773c860f8df1cf4.yaml
  test/unit/test_ibm_primitives.py
Labels: Changelog: New Feature

#966 Fix a typo (ltar -> later).
  docs/how_to/retrieve_results.rst
Labels: documentation
