Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-06, with the labels that each got.

#1746 Update deprecation msg with correct version
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
Labels: backport potential

#1739 Backend required param when using cloud channel
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/session.py
  test/integration/test_job.py
  test/unit/test_ibm_primitives.py
  test/unit/test_ibm_primitives_v2.py
  test/unit/test_runtime_ws.py
  test/unit/test_session.py
Labels: Changelog: Removal

#1755 Change use_fractional_gates default to False
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/1755.bug.rst
Labels: Changelog: Bugfix

#1740 Add refresh method to fake backends
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  qiskit_ibm_runtime/utils/backend_encoder.py
  release-notes/unreleased/1740.upgrade.rst
  test/integration/test_fake_backends.py
Labels: Changelog: New Feature

#1730 Add client-side validations
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/base_runtime_job.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_options.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/utils/__init__.py
  qiskit_ibm_runtime/utils/utils.py
  qiskit_ibm_runtime/utils/validations.py
  test/unit/test_estimator.py
  test/unit/test_sampler.py
Labels: Changelog: New Feature

#1764 Adding backend related methods to `QiskitRuntimeLocalService`
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  qiskit_ibm_runtime/fake_provider/local_service.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/1764.feat.rst
  test/unit/fake_provider/test_local_service.py
Labels: Changelog: New Feature

#1773 Support `default_shots` in EstimatorV2 local mode
  qiskit_ibm_runtime/fake_provider/local_service.py
  release-notes/unreleased/1773.feat.rst
  test/unit/test_local_mode.py
Labels: Changelog: New Feature

#1771 Add instance property to job
  qiskit_ibm_runtime/base_runtime_job.py
  release-notes/unreleased/1771.feat.rst
  test/integration/test_ibm_job_attributes.py
Labels: Changelog: New Feature
