Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-10, with the labels that each got.

#1960 Fix GitHub source code links for decorated functions
  docs/conf.py
Labels: documentation, backport potential

#1978 Adding `debug_tools` to API docs
  CONTRIBUTING.md
  docs/apidocs/debug_tools.rst
  docs/apidocs/index.rst
  qiskit_ibm_runtime/debug_tools/__init__.py
Labels: documentation

#1966 Remove channel strategy & q-ctrl
  .github/workflows/q-ctrl-tests.yml
  qiskit_ibm_runtime/accounts/account.py
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/fake_provider/local_service.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/utils/qctrl.py
  release-notes/unreleased/1966.other.rst
  test/decorators.py
  test/integration/test_account.py
  test/qctrl/test_qctrl.py
  test/unit/mock/fake_runtime_client.py
  test/unit/test_account.py
  test/unit/test_ibm_primitives_v2.py
  test/utils.py
Labels: Changelog: Removal

#1965 Remove 0.25 deprecations
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/options/estimator_options.py
  qiskit_ibm_runtime/options/options.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/runtime_job_v2.py
  release-notes/unreleased/1965.other.rst
  test/unit/test_estimator.py
  test/unit/test_estimator_options.py
  test/unit/test_jobs.py
  test/unit/test_options_utils.py
  test/unit/test_runtime_ws.py
  test/unit/test_sampler.py
Labels: Changelog: Removal

#1955 Add backend refresh() method
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/ibm_backend.py
  release-notes/unreleased/1955.feat.rst
  test/integration/test_backend.py
Labels: Changelog: New Feature

#1995 Add backend method
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/noise_learner/noise_learner.py
  release-notes/unreleased/1995.feat.rst
  test/unit/test_ibm_primitives_v2.py
  test/unit/test_noise_learner.py
Labels: Changelog: New Feature

#2008 Fix broken anchor links in release notes
  release-notes/0.1.0.rst
  release-notes/0.1.0rc1.rst
Labels: documentation, backport potential
