Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-12, with the labels that each got.

#2056 Add twirling stratgey options diagram
  docs/source_images/twirling_strategy_options.png
  qiskit_ibm_runtime/options/twirling_options.py
Labels: documentation

#2021 Verify values of parametrized rzz gates
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/utils/__init__.py
  qiskit_ibm_runtime/utils/utils.py
  qiskit_ibm_runtime/utils/validations.py
  release-notes/unreleased/2021.feat.rst
  test/unit/test_sampler.py
Labels: Changelog: New Feature

#2020 Update fake backend refresh()
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  release-notes/unreleased/2020.bug.rst
Labels: Changelog: Bugfix

#2048 Add try/except when creating backend obj
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/2048.bug.rst
Labels: Changelog: Bugfix
