Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-01, with the labels that each got.

#1293 Update grover tutorial equation
  docs/tutorials/grover_with_sampler.ipynb
Labels: documentation

#1291 Add dynamic circuits backend filter
  qiskit_ibm_runtime/qiskit_runtime_service.py
  releasenotes/notes/dynamic-circuits-filter-59f771a9b43c00cd.yaml
Labels: Changelog: New Feature

#1304 Update session_id docstring
  qiskit_ibm_runtime/session.py
Labels: documentation

#1308 Exclude params on job retrieval by default
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/runtime_job.py
  releasenotes/notes/exclude-job-params-default-00133498a5c5c15d.yaml
  test/integration/test_retrieve_job.py
  test/unit/mock/fake_runtime_client.py
Labels: Changelog: Bugfix

#1343 Add missing API Refs to docs
  docs/apidocs/fake_provider.rst
  docs/apidocs/ibm-runtime.rst
  docs/apidocs/transpiler.rst
  docs/conf.py
  qiskit_ibm_runtime/fake_provider/__init__.py
Labels: documentation, backport potential
