Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-04, with the labels that each got.

#1459 Add dosctring for Batch class
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/batch.py
Labels: documentation

#1575 Fix incorrect specification of noise_gain option
  qiskit_ibm_runtime/options/pec_options.py
Labels: Changelog: Bugfix

#1572 Allow user-specified function for producing a block ordering
  qiskit_ibm_runtime/transpiler/passes/scheduling/block_base_padder.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/pad_delay.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/scheduler.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/utils.py
  release-notes/unreleased/1531.feat.rst
  test/unit/transpiler/passes/scheduling/test_dynamical_decoupling.py
Labels: enhancement

#1494 Allow new job status' in RuntimeJobV2
  qiskit_ibm_runtime/runtime_job_v2.py
  release-notes/unreleased/1476.bug.rst
Labels: Changelog: Bugfix

#1568 Use status() for related methods
  qiskit_ibm_runtime/base_runtime_job.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/runtime_job_v2.py
  release-notes/unreleased/1547.bug.rst
Labels: Changelog: Bugfix

#1581 Add elapsed_time to session details
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1567.feat.rst
Labels: Changelog: New Feature

#1588 ZNE options validation fix
  qiskit_ibm_runtime/options/zne_options.py
  test/unit/test_estimator_options.py
Labels: Changelog: Bugfix

#1311 Update from_id()
  qiskit_ibm_runtime/api/rest/runtime_session.py
  qiskit_ibm_runtime/session.py
  test/integration/test_session.py
  test/unit/mock/fake_runtime_client.py
  test/unit/test_session.py
Labels: Changelog: Deprecation

#1592 Custom header not being sent
  qiskit_ibm_runtime/api/session.py
  release-notes/unreleased/1508.bug.rst
Labels: Changelog: Bugfix

#1580 Decode empty Databin's
  qiskit_ibm_runtime/utils/json.py
  test/unit/test_data_serialization.py
Labels: Changelog: Bugfix

#1591 Deprecate V1 primitives
  qiskit_ibm_runtime/base_primitive.py
Labels: on hold

#1593 Raise an error if dynamical decoupling is used with dynamic circuits
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/utils/__init__.py
  qiskit_ibm_runtime/utils/converters.py
  qiskit_ibm_runtime/utils/utils.py
  test/unit/test_estimator.py
  test/unit/test_sampler.py
Labels: Changelog: New Feature

#1596 Missing circuit metadata in PubResult from SamplerV2
  qiskit_ibm_runtime/qiskit/primitives/backend_sampler_v2.py
  test/unit/qiskit/test_backend_sampler_v2.py
Labels: Changelog: Bugfix

#1583 Add twirling options to SamplerV2
  qiskit_ibm_runtime/options/sampler_options.py
  qiskit_ibm_runtime/options/twirling_options.py
  release-notes/unreleased/1557.feat.rst
  test/unit/test_sampler_options.py
Labels: Changelog: New Feature, on hold

#1579 Deprecate backend.run
  qiskit_ibm_runtime/ibm_backend.py
  release-notes/unreleased/1561.deprecation.rst
  test/unit/test_backend.py
Labels: Changelog: Deprecation

#1584 Add mode parameter
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
  release-notes/unreleased/1556.deprecation.rst
  release-notes/unreleased/1556.feat.rst
  test/unit/test_ibm_primitives_v2.py
  test/unit/test_local_mode.py
  test/utils.py
Labels: Changelog: Deprecation, Changelog: New Feature

#1632 Small bugfix in resilience validation
  qiskit_ibm_runtime/options/resilience_options.py
  test/unit/test_estimator_options.py
Labels: Changelog: Bugfix

#1636 Make `name` a required param in backend()
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/1147.deprecation.rst
Labels: Changelog: Deprecation
