Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-05, with the labels that each got.

#1649 Link to every module in API index page
  docs/_templates/autosummary/module.rst
  docs/apidocs/index.rst
  docs/apidocs/qiskit_ibm_runtime.transpiler.passes.scheduling.rst
  docs/index.rst
  qiskit_ibm_runtime/transpiler/passes/__init__.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
Labels: documentation, backport potential

#1655 Fix URL for Qiskit Serverless
  release-notes/0.14.0.rst
Labels: documentation, backport potential

#1630 Fix multiple cycles of staggered DD
  qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py
  release-notes/unreleased/1630.bug.rst
  test/unit/transpiler/passes/scheduling/test_dynamical_decoupling.py
Labels: Changelog: New Feature

#1600 Replace `convert_to_target` with the Qiskit version
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/utils/backend_converter.py
  test/integration/test_backend.py
  test/unit/test_backend.py
  test/utils.py
Labels: Changelog: New Feature

#1524 Return correct job version
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/1471.bug.rst
  test/integration/test_retrieve_job.py
Labels: Changelog: Bugfix

#1289 Custom programs followup
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/base_runtime_job.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/exceptions.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/runtime_options.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1238.deprecation.rst
  test/ibm_test_case.py
  test/unit/mock/fake_runtime_client.py
Labels: Changelog: Deprecation

#1679 Add `resilience.zne.amplifier` to EstimatorV2 options
  qiskit_ibm_runtime/options/zne_options.py
  release-notes/unreleased/1679.feat.rst
  test/integration/test_estimator_v2.py
Labels: Changelog: New Feature

#1705 Add `private_endpoint` param when saving account
  qiskit_ibm_runtime/accounts/account.py
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/api/client_parameters.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/utils/utils.py
  release-notes/unreleased/1699.feat.rst
  test/unit/test_account.py
Labels: Changelog: New Feature
