Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-03, with the labels that each got.

#1477 Allow importing SamplerV1 and EstimatorV1
  qiskit_ibm_runtime/__init__.py
Labels: backport potential

#1479 Hacky fix for Reno removing 0.16+ release notes
  docs/release_notes.rst
Labels: backport potential

#1486 Fix unrelated release notes being added to 0.15 entry
  docs/release_notes.rst
Labels: backport potential

#1487 Add RuntimeJobV2 to docs
  qiskit_ibm_runtime/__init__.py
Labels: backport potential

#1510 Fix IBMBackend sphinx
  qiskit_ibm_runtime/ibm_backend.py
Labels: documentation, backport potential

#1409 Modify `skip_reset_qubits` to apply DD on all qubits when False
  qiskit_ibm_runtime/transpiler/passes/scheduling/block_base_padder.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py
  releasenotes/notes/dd-include-clean-qubits-710700437913509a.yaml
  test/unit/transpiler/passes/scheduling/test_dynamical_decoupling.py
Labels: Changelog: New Feature

#1495 Add local mode for v1 primitives
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/batch.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/fake_provider/local_service.py
  qiskit_ibm_runtime/options/utils.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_job_v2.py
  qiskit_ibm_runtime/runtime_options.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1495.feat.rst
  test/integration/test_estimator.py
  test/integration/test_sampler.py
  test/unit/test_batch.py
  test/unit/test_ibm_primitives.py
  test/unit/test_ibm_primitives_v2.py
  test/unit/test_local_mode.py
  test/unit/test_session.py
  test/utils.py
Labels: Changelog: New Feature

#1542 Treat resilience_level=0 for EstimatorV2 properly (replace of 1541)
  qiskit_ibm_runtime/options/options.py
  release-notes/unreleased/1541.bug.rst
  test/unit/test_estimator_options.py
  test/unit/test_sampler_options.py
Labels: Changelog: Bugfix

#1537 Remove runtime property
  qiskit_ibm_runtime/qiskit_runtime_service.py
Labels: Changelog: Removal

#1553 Fix render of IBM links in the release notes
  release-notes/0.1.0.rst
  release-notes/0.1.0rc1.rst
  release-notes/0.1.0rc2.rst
  release-notes/0.11.0.rst
  release-notes/0.11.1.rst
  release-notes/0.11.2.rst
  release-notes/0.11.3.rst
  release-notes/0.12.0.rst
  release-notes/0.12.1.rst
  release-notes/0.13.0.rst
  release-notes/0.14.0.rst
  release-notes/0.15.0.rst
  release-notes/0.15.1.rst
  release-notes/0.17.0.rst
  release-notes/0.18.0.rst
  release-notes/0.2.0.rst
  release-notes/0.20.0.rst
  release-notes/0.4.0.rst
  release-notes/0.5.0.rst
  release-notes/0.6.0.rst
  release-notes/0.7.0.rst
  release-notes/0.7.0rc1.rst
  release-notes/0.7.0rc2.rst
  release-notes/0.8.0.rst
  release-notes/0.9.0.rst
  release-notes/0.9.1.rst
  release-notes/0.9.2.rst
  release-notes/0.9.3.rst
  release-notes/0.9.4.rst
Labels: backport potential

#1550 feat: Add qctrl validation for Primitives v2
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/utils/qctrl.py
  release-notes/unreleased/1550.feat.rst
  test/unit/test_ibm_primitives_v2.py
Labels: Changelog: New Feature

#1538 Pretty print options
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/options/__init__.py
  qiskit_ibm_runtime/options/options.py
  release-notes/unreleased/1490.feat.rst
Labels: Changelog: New Feature
