Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-09, with the labels that each got.

#1896 Don't create new session in `from_id()`
  qiskit_ibm_runtime/batch.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1896.bug.rst
  test/unit/test_session.py
Labels: Changelog: Bugfix

#1909 Make `NoiseLearnerResult` JSON serializable
  qiskit_ibm_runtime/utils/json.py
  qiskit_ibm_runtime/utils/noise_learner_result.py
  release-notes/unreleased/1908.feat.rst
  test/unit/test_data_serialization.py
Labels: backport potential

#1914 add custom url resolver to enable using other endpoints
  qiskit_ibm_runtime/api/client_parameters.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/utils/__init__.py
  qiskit_ibm_runtime/utils/utils.py
  release-notes/unreleased/1914.deprecation.rst
  release-notes/unreleased/1914.feat.rst
  test/unit/test_client_parameters.py
Labels: Changelog: New Feature

#1920 Fix broken links in release notes
  release-notes/0.1.0.rst
  release-notes/0.18.0.rst
  release-notes/0.7.0.rst
  release-notes/0.7.0rc2.rst
  release-notes/0.8.0.rst
  release-notes/0.9.2.rst
  release-notes/0.9.4.rst
Labels: documentation, backport potential

#1922 Fix missing fractional gates in primitive in session
  qiskit_ibm_runtime/base_primitive.py
  release-notes/unreleased/1922.but.rst
  test/unit/test_session.py
Labels: Changelog: Bugfix

#1827 Add job usage method
  qiskit_ibm_runtime/base_runtime_job.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1827.feat.rst
Labels: Changelog: New Feature

#1931 Deprecate channel strategy
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/1931.deprecation.rst
Labels: Changelog: Deprecation

#1907 Remove 0.24.0 deprecations
  README.md
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/base_runtime_job.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/noise_learner/noise_learner.py
  qiskit_ibm_runtime/options/__init__.py
  qiskit_ibm_runtime/options/options.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1907.other.rst
  test/ibm_test_case.py
  test/integration/test_backend.py
  test/integration/test_estimator_v2.py
  test/integration/test_ibm_job.py
  test/integration/test_ibm_job_attributes.py
  test/integration/test_sampler_v2.py
  test/integration/test_session.py
  test/unit/test_batch.py
  test/unit/test_estimator.py
  test/unit/test_estimator_options.py
  test/unit/test_ibm_primitives_v2.py
  test/unit/test_job_retrieval.py
  test/unit/test_local_mode.py
  test/unit/test_noise_learner.py
  test/unit/test_sampler.py
  test/unit/test_sampler_options.py
  test/unit/test_session.py
Labels: Changelog: Removal

#1933 Deprecate returning JobStatus in RuntimeJob
  qiskit_ibm_runtime/runtime_job.py
  release-notes/unreleased/1933.deprecation.rst
Labels: Changelog: Deprecation

#1947 Fix broken anchor links in release notes
  release-notes/0.5.0.rst
  release-notes/0.7.0.rst
  release-notes/0.8.0.rst
  release-notes/0.9.1.rst
  release-notes/0.9.2.rst
  release-notes/0.9.3.rst
  release-notes/0.9.4.rst
Labels: documentation, backport potential

#1953 Enhance the ISA check with validation of rzz angle
  qiskit_ibm_runtime/fake_provider/backends/fractional/conf_fractional.json
  qiskit_ibm_runtime/utils/utils.py
  test/unit/test_sampler.py
Labels: Changelog: Bugfix

#1897 Use attribute docstrings for options
  qiskit_ibm_runtime/options/dynamical_decoupling_options.py
  qiskit_ibm_runtime/options/environment_options.py
  qiskit_ibm_runtime/options/estimator_options.py
  qiskit_ibm_runtime/options/layer_noise_learning_options.py
  qiskit_ibm_runtime/options/measure_noise_learning_options.py
  qiskit_ibm_runtime/options/pec_options.py
  qiskit_ibm_runtime/options/resilience_options.py
  qiskit_ibm_runtime/options/sampler_options.py
  qiskit_ibm_runtime/options/simulator_options.py
Labels: documentation
