Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-07, with the labels that each got.

#1776 Deprecate interim results
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/runtime_job_v2.py
  release-notes/unreleased/1776.deprecation.rst
Labels: Changelog: Deprecation

#1795 Add instance param to localService backend()
  qiskit_ibm_runtime/fake_provider/local_service.py
Labels: Changelog: Bugfix

#1765 Add more fake backend methods
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  release-notes/unreleased/1765.feat.rst
  test/integration/test_fake_backends.py
Labels: Changelog: New Feature

#1791 Don't cache target in target_history
  qiskit_ibm_runtime/ibm_backend.py
  release-notes/unreleased/1791.bug.rst
  test/unit/mock/fake_runtime_client.py
Labels: Changelog: Bugfix

#1804 Deprecate passing backend as a string
  qiskit_ibm_runtime/batch.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1804.deprecation.rst
Labels: Changelog: Deprecation

#1794 Wait for job if maximum pending jobs limit is exceeded
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/1794.feat.rst
Labels: Changelog: New Feature

#1793 Add local channel
  qiskit_ibm_runtime/accounts/account.py
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  qiskit_ibm_runtime/fake_provider/local_service.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1793.feat.rst
  test/integration/test_account.py
  test/unit/mock/fake_runtime_service.py
  test/unit/test_ibm_primitives.py
  test/unit/test_ibm_primitives_v2.py
Labels: Changelog: New Feature

#1816 Add deprecation msg for session precendence
  qiskit_ibm_runtime/base_primitive.py
  release-notes/unreleased/1816.deprecation.rst
  test/integration/test_session.py
Labels: Changelog: Deprecation

#1800 Fix simplejson incompatibility
  qiskit_ibm_runtime/utils/json.py
  release-notes/unreleased/1800.bug.rst
  test/integration/test_job.py
Labels: Changelog: Bugfix

#1826 Deprecate `service` in session & batch
  qiskit_ibm_runtime/batch.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/1826.deprecation.rst
Labels: Changelog: Deprecation

#1805 Adding NoiseLearner class and related functionality
  docs/apidocs/index.rst
  docs/apidocs/noise_learner.rst
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/constants.py
  qiskit_ibm_runtime/noise_learner/__init__.py
  qiskit_ibm_runtime/noise_learner/noise_learner.py
  qiskit_ibm_runtime/options/__init__.py
  qiskit_ibm_runtime/options/noise_learner_options.py
  qiskit_ibm_runtime/utils/noise_learner_result.py
  qiskit_ibm_runtime/utils/noise_learner_result_decoder.py
  release-notes/unreleased/1805.feat.rst
  test/integration/test_noise_learner.py
  test/unit/test_noise_learner.py
  test/unit/test_noise_learner_options.py
Labels: Changelog: New Feature
