Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-02, with the labels that each got.

#1363 Handle Qiskit 1.0 removals
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  qiskit_ibm_runtime/qpy/binary_io/circuits.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/dynamical_decoupling.py
  test/integration/test_options.py
  test/unit/mock/fake_api_backend.py
  test/unit/test_backend.py
  test/unit/test_backend_retrieval.py
  test/unit/test_data_serialization.py
  test/unit/test_ibm_primitives.py
  test/unit/test_options.py
  test/unit/test_runtime_ws.py
  test/unit/test_session.py
  test/unit/transpiler/passes/scheduling/control_flow_test_case.py
  test/unit/transpiler/passes/scheduling/test_dynamical_decoupling.py
  test/unit/transpiler/passes/scheduling/test_scheduler.py
Labels: Qiskit 1.0

#1377 Handle qpy serialization across versions and delete vendored fork
  qiskit_ibm_runtime/qpy/__init__.py
  qiskit_ibm_runtime/qpy/binary_io/__init__.py
  qiskit_ibm_runtime/qpy/binary_io/circuits.py
  qiskit_ibm_runtime/qpy/binary_io/schedules.py
  qiskit_ibm_runtime/qpy/binary_io/value.py
  qiskit_ibm_runtime/qpy/common.py
  qiskit_ibm_runtime/qpy/exceptions.py
  qiskit_ibm_runtime/qpy/formats.py
  qiskit_ibm_runtime/qpy/interface.py
  qiskit_ibm_runtime/qpy/type_keys.py
  qiskit_ibm_runtime/utils/json.py
Labels: Qiskit 1.0

#1385 Cast use_symengine input to a bool
  qiskit_ibm_runtime/utils/json.py
Labels: priority: high, Qiskit 1.0

#1397 Remove remaining qiskit.org links
  docs/tutorials/how-to-getting-started-with-estimator.ipynb
  docs/tutorials/how-to-getting-started-with-sampler.ipynb
  qiskit_ibm_runtime/provider_session.py
  setup.py
Labels: backport potential

#1347 Support Python 3.12
  .github/workflows/ci.yml
  pyproject.toml
  releasenotes/notes/python-3-12-support-a0390cacfe596e5b.yaml
  requirements-dev.txt
  setup.py
  tox.ini
Labels: Changelog: New Feature

#1378 Fix scheduling in control flow with instructions of non-uniform durations
  qiskit_ibm_runtime/transpiler/passes/scheduling/__init__.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/block_base_padder.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/pad_delay.py
  qiskit_ibm_runtime/transpiler/passes/scheduling/scheduler.py
  releasenotes/notes/fix-durations-with-control-flow-0cf6b5c48c387ca8.yaml
  test/unit/transpiler/passes/scheduling/test_scheduler.py
Labels: Changelog: Bugfix

#1404 Add deprecation warning for abstract circuits
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/utils/backend_decoder.py
  qiskit_ibm_runtime/utils/utils.py
  releasenotes/notes/deprecate-abstract-circuits-d9bdc94b2be7ea21.yaml
Labels: Changelog: Deprecation

#1372 Use POST /sessions endpoint
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/api/rest/runtime_session.py
  qiskit_ibm_runtime/batch.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/session.py
  qiskit_ibm_runtime/utils/json.py
  releasenotes/notes/session-modes-5c22b68620f8d690.yaml
  test/integration/test_session.py
  test/unit/mock/fake_runtime_client.py
  test/unit/test_batch.py
  test/unit/test_runtime_ws.py
  test/unit/test_session.py
Labels: Changelog: New Feature

#1402 Fix bug with retrieving fake backends
  qiskit_ibm_runtime/fake_provider/fake_provider.py
  releasenotes/notes/retrieve-fake-backend-13fd3088aaac69e5.yaml
  test/unit/fake_provider/test_fake_backends.py
Labels: Changelog: Bugfix

#1430 Update sessions mode release note
  releasenotes/notes/0.20/session-modes-5c22b68620f8d690.yaml
Labels: backport potential

#1425 Add warning if no backend provided on cloud channel
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/session.py
  releasenotes/notes/require-cloud-backend-38a74144347c735d.yaml
  test/unit/test_session.py
Labels: Changelog: Deprecation

#1431 Use sphinx.ext.linkcode for more precise source code links
  .gitignore
  docs/conf.py
  tox.ini
Labels: documentation, backport potential

#1445 Fix bad tox.ini passenv setting
  tox.ini
Labels: backport potential

#1443 Handle control flow instructions in Target generation
  qiskit_ibm_runtime/utils/backend_converter.py
  releasenotes/notes/fix-control-flow-d5a61dd5647acb42.yaml
  test/unit/test_backend.py
Labels: Changelog: Bugfix

#1440 Add fake backends for newer IBM backends
  qiskit_ibm_runtime/fake_provider/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/algiers/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/algiers/conf_algiers.json
  qiskit_ibm_runtime/fake_provider/backends/algiers/defs_algiers.json
  qiskit_ibm_runtime/fake_provider/backends/algiers/fake_algiers.py
  qiskit_ibm_runtime/fake_provider/backends/algiers/props_algiers.json
  qiskit_ibm_runtime/fake_provider/backends/brisbane/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/brisbane/conf_brisbane.json
  qiskit_ibm_runtime/fake_provider/backends/brisbane/defs_brisbane.json
  qiskit_ibm_runtime/fake_provider/backends/brisbane/fake_brisbane.py
  qiskit_ibm_runtime/fake_provider/backends/brisbane/props_brisbane.json
  qiskit_ibm_runtime/fake_provider/backends/cusco/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/cusco/conf_cusco.json
  qiskit_ibm_runtime/fake_provider/backends/cusco/defs_cusco.json
  qiskit_ibm_runtime/fake_provider/backends/cusco/fake_cusco.py
  qiskit_ibm_runtime/fake_provider/backends/cusco/props_cusco.json
  qiskit_ibm_runtime/fake_provider/backends/kawasaki/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/kawasaki/conf_kawasaki.json
  qiskit_ibm_runtime/fake_provider/backends/kawasaki/defs_kawasaki.json
  qiskit_ibm_runtime/fake_provider/backends/kawasaki/fake_kawasaki.py
  qiskit_ibm_runtime/fake_provider/backends/kawasaki/props_kawasaki.json
  qiskit_ibm_runtime/fake_provider/backends/kyiv/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/kyiv/conf_kyiv.json
  qiskit_ibm_runtime/fake_provider/backends/kyiv/defs_kyiv.json
  qiskit_ibm_runtime/fake_provider/backends/kyiv/fake_kyiv.py
  qiskit_ibm_runtime/fake_provider/backends/kyiv/props_kyiv.json
  qiskit_ibm_runtime/fake_provider/backends/kyoto/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/kyoto/conf_kyoto.json
  qiskit_ibm_runtime/fake_provider/backends/kyoto/defs_kyoto.json
  qiskit_ibm_runtime/fake_provider/backends/kyoto/fake_kyoto.py
  qiskit_ibm_runtime/fake_provider/backends/kyoto/props_kyoto.json
  qiskit_ibm_runtime/fake_provider/backends/osaka/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/osaka/conf_osaka.json
  qiskit_ibm_runtime/fake_provider/backends/osaka/defs_osaka.json
  qiskit_ibm_runtime/fake_provider/backends/osaka/fake_osaka.py
  qiskit_ibm_runtime/fake_provider/backends/osaka/props_osaka.json
  qiskit_ibm_runtime/fake_provider/backends/peekskill/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/peekskill/conf_peekskill.json
  qiskit_ibm_runtime/fake_provider/backends/peekskill/defs_peekskill.json
  qiskit_ibm_runtime/fake_provider/backends/peekskill/fake_peekskill.py
  qiskit_ibm_runtime/fake_provider/backends/peekskill/props_peekskill.json
  qiskit_ibm_runtime/fake_provider/backends/quebec/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/quebec/conf_quebec.json
  qiskit_ibm_runtime/fake_provider/backends/quebec/defs_quebec.json
  qiskit_ibm_runtime/fake_provider/backends/quebec/fake_quebec.py
  qiskit_ibm_runtime/fake_provider/backends/quebec/props_quebec.json
  qiskit_ibm_runtime/fake_provider/backends/torino/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/torino/conf_torino.json
  qiskit_ibm_runtime/fake_provider/backends/torino/defs_torino.json
  qiskit_ibm_runtime/fake_provider/backends/torino/fake_torino.py
  qiskit_ibm_runtime/fake_provider/backends/torino/props_torino.json
  qiskit_ibm_runtime/fake_provider/fake_provider.py
Labels: Changelog: New Feature
