Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-08, with the labels that each got.

#1841 Add warning about backend module change
  release-notes/0.26.0.rst
Labels: backport potential

#1823 Make PEA option public
  qiskit_ibm_runtime/options/zne_options.py
  test/unit/test_estimator_options.py
Labels: Changelog: New Feature

#1860 Remove V1 Primitive Support
  qiskit_ibm_runtime/__init__.py
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/fake_provider/local_service.py
  qiskit_ibm_runtime/options/__init__.py
  qiskit_ibm_runtime/options/execution_options.py
  qiskit_ibm_runtime/options/options.py
  qiskit_ibm_runtime/options/resilience_options.py
  qiskit_ibm_runtime/options/transpilation_options.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/utils/estimator_result_decoder.py
  qiskit_ibm_runtime/utils/qctrl.py
  qiskit_ibm_runtime/utils/sampler_result_decoder.py
  release-notes/unreleased/1857.other.rst
  test/ibm_test_case.py
  test/integration/test_estimator.py
  test/integration/test_job.py
  test/integration/test_options.py
  test/integration/test_retrieve_job.py
  test/integration/test_sampler.py
  test/integration/test_session.py
  test/qctrl/test_qctrl.py
  test/unit/test_estimator.py
  test/unit/test_ibm_primitives.py
  test/unit/test_local_mode.py
  test/unit/test_options.py
  test/unit/test_options_utils.py
  test/unit/test_sampler.py
  test/utils.py
Labels: Changelog: Removal

#1858 Exposing `layer_noise_model` option
  docs/apidocs/index.rst
  docs/apidocs/noise_learner_result.rst
  qiskit_ibm_runtime/options/resilience_options.py
  qiskit_ibm_runtime/utils/noise_learner_result.py
  release-notes/unreleased/1858.feat.rst
  test/integration/test_noise_learner.py
Labels: Changelog: New Feature

#1872 Add back alias docs pages for Sampler and Estimator
  qiskit_ibm_runtime/__init__.py
Labels: documentation, backport potential

#1876 Fix 404 link in release note
  release-notes/0.12.1.rst
Labels: documentation, backport potential

#1878 Minor release note typo
  release-notes/0.28.0.rst
Labels: backport potential

#1883 Fix zne options doc
  qiskit_ibm_runtime/options/zne_options.py
Labels: backport potential

#1879 Exposing `NoiseLearnerOptions` in docs
  qiskit_ibm_runtime/options/__init__.py
Labels: documentation, backport potential

#1884 Docs: clarify shots, default_shots, and twirling shots
  qiskit_ibm_runtime/options/twirling_options.py
  qiskit_ibm_runtime/options/zne_options.py
Labels: documentation, backport potential

#1892 Deprecate simulator `noise_model` option
  qiskit_ibm_runtime/base_primitive.py
  release-notes/unreleased/1892.deprecation.rst
Labels: Changelog: Deprecation
