Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2024-11, with the labels that each got.

#2011 Add execution_span.TwirledSliceSpan
  qiskit_ibm_runtime/execution_span/__init__.py
  qiskit_ibm_runtime/execution_span/double_slice_span.py
  qiskit_ibm_runtime/execution_span/twirled_slice_span.py
  qiskit_ibm_runtime/utils/json.py
  release-notes/unreleased/2011.feat.rst
  test/unit/test_data_serialization.py
  test/unit/test_execution_span.py
Labels: Changelog: New Feature

#1957 Don't cache in target_history()
  qiskit_ibm_runtime/ibm_backend.py
  test/integration/test_backend.py
Labels: Changelog: Bugfix

#2012 Replace fake backend utility methods
  qiskit_ibm_runtime/fake_provider/backends/melbourne/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/melbourne/fake_melbourne.py
  qiskit_ibm_runtime/fake_provider/backends/poughkeepsie/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/poughkeepsie/fake_poughkeepsie.py
  qiskit_ibm_runtime/fake_provider/backends/rueschlikon/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/rueschlikon/fake_rueschlikon.py
  qiskit_ibm_runtime/fake_provider/backends/tenerife/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/tenerife/fake_tenerife.py
  qiskit_ibm_runtime/fake_provider/backends/tenerife/props_tenerife.json
  qiskit_ibm_runtime/fake_provider/backends/tokyo/__init__.py
  qiskit_ibm_runtime/fake_provider/backends/tokyo/fake_tokyo.py
  qiskit_ibm_runtime/fake_provider/backends/tokyo/props_tokyo.json
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  qiskit_ibm_runtime/utils/backend_decoder.py
  release-notes/unreleased/2012.other.rst
Labels: Changelog: Removal

#2028 Add a private alias to decode_backend_configuration()
  qiskit_ibm_runtime/utils/backend_decoder.py
Labels: backport potential

#2026 Add CouplingMap to encoder
  qiskit_ibm_runtime/utils/json.py
  release-notes/unreleased/2026.bug.rst
Labels: Changelog: Bugfix

#2040 Adding swarm plotter to the docs
  qiskit_ibm_runtime/utils/noise_learner_result.py
  qiskit_ibm_runtime/visualization/__init__.py
Labels: documentation, backport potential

#1990 Add support for noise model and level 1 data to local sampler
  qiskit_ibm_runtime/fake_provider/local_service.py
  release-notes/unreleased/1990.feat.rst
  test/unit/test_sampler.py
Labels: Changelog: New Feature

#2027 Remove 0.26.0 deprecations
  qiskit_ibm_runtime/base_primitive.py
  qiskit_ibm_runtime/batch.py
  qiskit_ibm_runtime/estimator.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/sampler.py
  qiskit_ibm_runtime/session.py
  release-notes/unreleased/2027.other.rst
  test/integration/test_estimator_v2.py
  test/integration/test_noise_learner.py
  test/integration/test_sampler_v2.py
  test/integration/test_session.py
  test/unit/test_batch.py
  test/unit/test_estimator.py
  test/unit/test_ibm_primitives_v2.py
  test/unit/test_sampler.py
  test/unit/test_session.py
  test/utils.py
Labels: Changelog: Removal
