Repository Qiskit/qiskit-ibm-runtime, pull requests merged in 2025-07, with the labels that each got.

#2289 Remove IQP Classic
  README.md
  qiskit_ibm_runtime/accounts/account.py
  qiskit_ibm_runtime/accounts/management.py
  qiskit_ibm_runtime/api/auth.py
  qiskit_ibm_runtime/api/client_parameters.py
  qiskit_ibm_runtime/api/clients/__init__.py
  qiskit_ibm_runtime/api/clients/auth.py
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/root.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/api/rest/runtime_session.py
  qiskit_ibm_runtime/base_runtime_job.py
  qiskit_ibm_runtime/batch.py
  qiskit_ibm_runtime/constants.py
  qiskit_ibm_runtime/fake_provider/fake_backend.py
  qiskit_ibm_runtime/hub_group_project.py
  qiskit_ibm_runtime/ibm_backend.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  qiskit_ibm_runtime/runtime_job.py
  qiskit_ibm_runtime/runtime_options.py
  qiskit_ibm_runtime/session.py
  qiskit_ibm_runtime/utils/hgp.py
  qiskit_ibm_runtime/utils/queueinfo.py
  release-notes/unreleased/2289.upgrade.rst
  test/account.py
  test/decorators.py
  test/integration/test_account.py
  test/integration/test_backend.py
  test/integration/test_backend_serialization.py
  test/unit/mock/fake_api_backend.py
  test/unit/mock/fake_quantum_auth_client.py
  test/unit/mock/fake_runtime_client.py
  test/unit/mock/fake_runtime_service.py
  test/unit/test_account.py
  test/unit/test_backend_retrieval.py
  test/unit/test_client_parameters.py
  test/unit/test_data_serialization.py
  test/unit/test_job_retrieval.py
  test/unit/test_jobs.py
  test/unit/test_options.py
  test/unit/test_runtime_client.py
  test/unit/test_sampler.py
  test/unit/test_session.py
  test/utils.py
Labels: Changelog: Removal

#2331 Update error message if no saved accounts are found
  qiskit_ibm_runtime/accounts/management.py
Labels: Changelog: None

#2332 Allow `saved_accounts()` to return even if legacy accounts are saved
  qiskit_ibm_runtime/accounts/management.py
  test/unit/test_account.py
Labels: Changelog: Bugfix

#2329 Update usage method to include remaining usage
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/2329.feat.rst
  test/integration/test_account.py
Labels: Changelog: New Feature

#2337 Update test_service_usage
  test/integration/test_account.py
Labels: Changelog: None, type: QA

#2338 Fail gracefully when pub is not in span
  qiskit_ibm_runtime/execution_span/double_slice_span.py
  qiskit_ibm_runtime/execution_span/execution_span.py
  qiskit_ibm_runtime/execution_span/slice_span.py
  qiskit_ibm_runtime/execution_span/twirled_slice_span.py
  release-notes/unreleased/2311.other.rst
  test/unit/test_execution_span.py
Labels: Changelog: New Feature

#2336 Added pub shots in twirled slice span
  qiskit_ibm_runtime/execution_span/twirled_slice_span.py
  qiskit_ibm_runtime/utils/json.py
  release-notes/unreleased/2312.bug.rst
  test/unit/test_data_serialization.py
  test/unit/test_execution_span.py
Labels: Changelog: Bugfix

#2323 Update least_busy
  qiskit_ibm_runtime/api/clients/runtime.py
  qiskit_ibm_runtime/api/rest/base.py
  qiskit_ibm_runtime/api/rest/runtime.py
  qiskit_ibm_runtime/qiskit_runtime_service.py
  release-notes/unreleased/2323.feat.rst
  test/integration/test_backend.py
  test/unit/mock/fake_runtime_service.py
  test/unit/test_backend_retrieval.py
Labels: enhancement, Changelog: New Feature
